### PR TITLE
new jenkins.yml

### PR DESCRIPTION
**Pull request by witokondoria**

### CODE REVIEW

**Comment by witokondoria** [comment]
:shipit:, testing rebase

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/common-utils/420/)

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/common-utils/423/)

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/common-utils/424/)

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/common-utils/442/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/common-utils/461/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
A job will handle this PR ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/common-utils/478/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
